### ISSUE TITLE
Search functionality improvement needed

### ISSUE THREAD

**Issue by secult** [erigones/esdc-docs#24]
I started to notice a pattern in Danube Cloud GUI users behavior:

1. User doesn't understand something, so he opens docs.danubecloud.org
2. "Search docs" feature looks promising, so he copy paste or write down some keywords from the original screen.
3. User is dissapointed by the search results. While he is used to the common structure with headline and highlighted query found within a document fragment, he gets only topic headlines instead.
4. Afterwards he start to open found documents, full text searching the text occurrences with help of the browser, one by one.

It would be beneficial to improve the search result structure with the highlighting in the document fragment, adding the document hierarchical structure or visible url to the search result, etc.

**Comment by dn0** [comment]
In https://github.com/erigones/sphinx_rtd_theme we are behind the upstream. Wasn't this fixed in the upstream?

**Comment by secult** [comment]
Partially. There is a working demo http://docs.readthedocs.io/en/latest/index.html where when the search is used, you get at least the highlighted query in the document fragment. It may be good enough for now to match the upsteam.

**Comment by dn0** [comment]
I've updated the Sphinx RTD theme on docs.danubecloud.org and also fixed the web server configuration, which cause the search functionality to misbehave.
